# Generated by Django 5.0.2 on 2024-02-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketers',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('jersey_no', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('team', models.CharField(max_length=50)),
                ('total_matches_played', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bowling_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_bowled', models.PositiveIntegerField()),
                ('wickets_taken', models.PositiveSmallIntegerField()),
                ('bowling_style', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_app.cricketers')),
            ],
        ),
        migrations.CreateModel(
            name='Batting_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.PositiveBigIntegerField()),
                ('innings_played', models.PositiveIntegerField()),
                ('total_runs', models.PositiveBigIntegerField()),
                ('batting_style', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_app.cricketers')),
            ],
        ),
    ]
