# Generated by Django 5.0.2 on 2024-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketers',
            name='player_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
