# Generated by Django 5.0.2 on 2024-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0002_alter_cricketers_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting_record',
            name='runs_scored',
        ),
        migrations.AlterField(
            model_name='batting_record',
            name='total_runs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bowling_record',
            name='wickets_taken',
            field=models.PositiveIntegerField(),
        ),
    ]
